export const QUERY_KEY = {
  GET_ME: "user",
  GET_USERS: "users",
  APPROVE_USER: "approve-user",
  REJECT_USER: "reject-user",
  UN_APPROVE_USER: "unapprove-user",
  GET_JOB: "job",
  GET_JOBS: "jobs",
  APPROVE_JOB: "approve-job",
  UN_APPROVE_JOB: "unapprove-job",
  REJECT_JOB: "reject-job",
  GET_PUBLIC_JOB: "public-job",
  GET_INDUSTRIES: "industries",
  GET_PROVINCES: "provinces",
  GET_JOB_CATEGORIES: "job-categories",
  GET_JOBS_BY_COMPANY: "company-jobs",
  GET_JOBS_APPLIED: "jobs-applied",
  GET_JOB_APPLIED: "job-applied",
  GET_JOBS_FAVORITED: "jobs-favorited",
  GET_TESTIMONIALS: "testimonials",
  GET_RESUME_TEMPLATES: "resume-templates",
  GET_USER_RESUMES: "user-resumes",
} as const;
