export const QUERY_KEY = {
  GET_ME: "user",
  GET_USERS: "users",
  APPROVE_USER: "approve-user",
  REJECT_USER: "reject-user",
  UN_APPROVE_USER: "unapprove-user",
  GET_JOB: "job",
  GET_JOBS: "jobs",
  APPROVE_JOB: "approve-job",
  UN_APPROVE_JOB: "unapprove-job",
  REJECT_JOB: "reject-job",
  GET_PUBLIC_JOB: "public-job",
  GET_INDUSTRIES: "industries",
  GET_PROVINCES: "provinces",
  GET_JOB_CATEGORIES: "job-categories",
} as const;
